site_name: "MeshCentral Documentation"

nav:
  - Home:
    - 'Abstract': 'index.md'

  - 'Install':
    - 'Abstract': 'install/abstract.md'
    - 'Quickstart': 'install/quickstart.md'
    - 'Installation Guides':
        - 'Abstract': 'install/abstract.md'
        - 'Advanced': 'install/advanced.md'
        - 'Container (Docker)': 'install/container.md'
        - 'Windows': 'install/windows.md'
    - 'Databases':
      - 'MongoDB': 'install/database/mongodb.md'
      - 'PostgreSQL': 'install/database/postgresql.md'
      - 'MariaDB/MySQL': 'install/database/mariadb.md'
      - 'Local Databases': 'install/database/local.md'
    - 'Security':
      - 'Crowdsec': 'install/security/crowdsec.md'
      - 'Secure Installation': 'install/security/secure.md'

  - 'MeshCentral':
    - 'MeshCentral Guide': 'meshcentral/'
    - 'All Configuration Options': 'meshcentral/config.md'
    - 'SSL/TLS': 'meshcentral/SSLnletsencrypt.md'
    - 'Agent Information': 'meshcentral/agents.md'
    - 'Assistant': 'meshcentral/assistant.md'
    - 'Code Signing': 'meshcentral/codesigning.md'
    - 'Debugging': 'meshcentral/debugging.md'
    - 'Device Tabs': 'meshcentral/devicetabs.md'
    - 'Plugins': 'meshcentral/plugins.md'
    - 'Security': 'meshcentral/security.md'
    - 'Tokens': 'meshcentral/tokens.md'
    - 'FAQ': 'meshcentral/faq.md'
    - 'Tips n Tricks': 'meshcentral/tipsntricks.md'
    - 'Messaging': 'messaging/'
    - 'Customization': 'meshcentral/customization.md'
    - 'OpenID Connect Strategy (OIDC)': 'meshcentral/openidConnectStrategy.md'

  - 'Submodules and Features':
    - 'MeshCmd': 'meshcmd/'
    - 'MeshCtrl': 'meshctrl/'
    - 'Mesh Router': 'meshrouter/'
    - 'Intel AMT': 'intelamt/'

  - 'How to Contribute': 'how-to-contribute/'

  - 'Design and Architecture': 'design/'

  - 'Other':
    - 'other/adfs_sso_guide.md' 
    - 'other/meshcentral_satellite.md'

site_description: "A remote monitoring and management tool"
site_author: "Ylianst and contributors"
site_url: "https://ylianst.github.io/MeshCentral/"

dev_addr: "0.0.0.0:8010"

# Repository
repo_name: "Ylianst/MeshCentral"
repo_url: "https://github.com/Ylianst/MeshCentral"

theme:
  name: "material"
  logo: "images/favicon.ico"
  favicon: "images/favicon.ico"
  language: en
  locale: en
  include_sidebar: false
  palette:
    - scheme: default # Palette toggle for dark mode
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - scheme: slate # Palette toggle for light mode
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
  features:
    - content.code.copy
    - content.code.select
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.instant
    - search.suggest
extra_css:
  - stylesheets/extra.css
extra:
  generator: false
plugins:
  - search
  - print-site

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - tables

# to-do later on down the line; migrate to zensical.toml in an ideal world